version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - run:
          name: Add GitHub as known host
          command: mkdir -p ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: Install pygraphviz
          command: sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest --durations=0 --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
  deploy:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Add GitHub as known host
          command: mkdir -p ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: Build Docker image
          command: docker build . -t iarcuschin/circuits-benchmark
      - run:
          name: Publish Docker image
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            docker push iarcuschin/circuits-benchmark

workflows:
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*experiments$/
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - test