# runner.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: {NAME}
    spec:
      priorityClassName: {PRIORITY}
      containers:
      - name: devbox-container
        image: docker.io/iarcuschin/circuits-benchmark:latest
        command: {COMMAND}
        resources:
          requests:
            cpu: {CPU}
          limits:
            memory: {MEMORY}
            nvidia.com/gpu: {GPU}
        env:
          - name: OMP_NUM_THREADS
            value: {OMP_NUM_THREADS}
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb
                key: api-key
          - name: WANDB_DISABLE_SERVICE
            value: "true"
      restartPolicy: Never  # Do not restart on failure of the main command
  backoffLimit: 0  # Do not retry if the main command errors
  # But *do* make the Job create another Pod if it gets preempted by something else.
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget
